version: "3.4"

services:
  spreadsheet-server:
    container_name: spreadsheet-server
    build: . # Uses local Dockerfile
    environment:
      SYNCFUSION_LICENSE_KEY: ${SYNCFUSION_LICENSE_KEY}
      LC_ALL: de_DE.UTF-8
      LANGUAGE: de_DE.UTF-8
      LANG: de_DE.UTF-8
    depends_on:
      - nginx
    # Removed port exposure - now internal only

  nginx:
    image: docker.io/library/nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  # Add a shared network for internal communication
