services:
  spreadsheet-server:
    container_name: spreadsheet-server
    build: . # Uses local Dockerfile
    environment:
      SYNCFUSION_LICENSE_KEY: ${SYNCFUSION_LICENSE_KEY}
      LC_ALL: de_DE.UTF-8
      LANGUAGE: de_DE.UTF-8
      LANG: de_DE.UTF-8
    depends_on:
      - nginx
    # Removed port exposure - now internal only

  nginx:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./nginx-data:/data
      - ./nginx-letsencrypt:/etc/letsencrypt

  # Add a shared network for internal communication
